"""
models/schemas.py

All Pydantic models used across pr_lens agents.
Every agent returns a typed output — no raw string blobs.

Flow:
  PRContext         → RunContextWrapper payload, passed to every agent
  SummaryOutput     → returned by summary_agent
  SecurityOutput    → returned by security_agent
  QualityOutput     → returned by quality_agent
  ReviewReport      → final assembled report from synthesis_agent
"""

from enum import Enum
from pydantic import BaseModel, Field


# ── Shared context ─────────────────────────────────────────────────────────────

class PRContext(BaseModel):
    """
    Typed context carried through the entire agent run via RunContextWrapper.
    Parsed from the user's input by pr_parser before Runner.run() is called.
    """
    owner: str
    repo: str
    pr_number: int

    @property
    def repo_full(self) -> str:
        return f"{self.owner}/{self.repo}"

    @property
    def pr_ref(self) -> str:
        return f"{self.owner}/{self.repo}#{self.pr_number}"


# ── Specialist outputs (structured — returned as agent output_type) ────────────

class SummaryOutput(BaseModel):
    """Returned by summary_agent."""
    what_changed: str = Field(description="Plain-english description of what changed in this PR")
    why: str = Field(description="Inferred reason or motivation for the change")
    files_touched: list[str] = Field(description="Key files that were modified")
    complexity: str = Field(description="One of: trivial | small | medium | large | very large")


class SecurityFinding(BaseModel):
    severity: str = Field(description="One of: critical | high | medium | low | info")
    file: str = Field(description="File where the issue was found, or 'general'")
    line: str = Field(description="Line number or range if known, else 'unknown'")
    description: str = Field(description="What the issue is and why it matters")


class SecurityOutput(BaseModel):
    """Returned by security_agent."""
    findings: list[SecurityFinding] = Field(default_factory=list)
    passed: bool = Field(description="True if no critical or high severity findings")
    summary: str = Field(description="One-sentence overall security assessment")


class QualityFinding(BaseModel):
    category: str = Field(description="One of: complexity | duplication | naming | structure | test_coverage | other")
    file: str = Field(description="File where the issue was found, or 'general'")
    description: str = Field(description="What the quality issue is")
    suggestion: str = Field(description="Concrete suggestion to improve it")


class QualityOutput(BaseModel):
    """Returned by quality_agent."""
    findings: list[QualityFinding] = Field(default_factory=list)
    passed: bool = Field(description="True if no significant quality concerns")
    summary: str = Field(description="One-sentence overall quality assessment")


# ── Final report (assembled by synthesis_agent) ────────────────────────────────

class Verdict(str, Enum):
    APPROVE          = "approve"
    REQUEST_CHANGES  = "request_changes"
    NEEDS_DISCUSSION = "needs_discussion"


class ReviewReport(BaseModel):
    """
    Final structured output from synthesis_agent.
    output_guardrail enforces verdict is always present.
    markdown_report and email_html are generated by the LLM as part of
    the structured output — no markdown formatting in instructions needed.
    """
    pr_ref: str = Field(description="e.g. owner/repo#123")
    pr_title: str = Field(description="Title of the pull request")
    author: str
    files_changed: int
    additions: int
    deletions: int
 
    summary: SummaryOutput
    security: SecurityOutput
    quality: QualityOutput
 
    verdict: Verdict = Field(description="Overall review decision")
    verdict_reason: str = Field(description="1-2 sentence explanation of the verdict")
 
    markdown_report: str = Field(
        description=(
            "A complete well-structured markdown PR review report. "
            "Include sections: Summary, Security Review, Code Quality, and Verdict. "
            "Use emojis and headers. Be thorough but readable."
        )
    )
    email_html: str = Field(
        description=(
            "The markdown_report converted to simple HTML for email delivery. "
            "Replace newlines with <br> tags. Keep it clean and readable."
        )
    )